import {
  AlertTriangle,
  ArrowRight,
  BookOpen,
  Bookmark,
  Check,
  ChevronLeft,
  ChevronRight,
  Copy,
  Database,
  Ellipsis,
  FileText,
  Globe2,
  GitFork,
  GitMerge,
  House,
  LibraryBig,
  ListTree,
  Map,
  Maximize2,
  Menu,
  MessageSquare,
  Minimize2,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRight,
  Paperclip,
  PenLine,
  RefreshCw,
  Route,
  Search,
  SendHorizontal,
  Settings2,
  Sparkles,
  SquarePen,
  Sun,
  Type,
  Trash2,
  Users,
  X,
} from "@lucide/vue";
import type {Component} from "vue";

/**
 * Semantic icon names used by the product. The underlying artwork can evolve
 * without leaking library-specific names into feature components.
 */
export const gameIcons = {
  alert: AlertTriangle,
  home: House,
  pen: PenLine,
  "book-open": BookOpen,
  library: LibraryBig,
  database: Database,
  sparkles: Sparkles,
  "file-text": FileText,
  globe: Globe2,
  users: Users,
  message: MessageSquare,
  attachment: Paperclip,
  map: Map,
  settings: Settings2,
  more: Ellipsis,
  search: Search,
  bookmark: Bookmark,
  list: ListTree,
  sun: Sun,
  type: Type,
  fullscreen: Maximize2,
  close: X,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "fullscreen-exit": Minimize2,
  edit: SquarePen,
  check: Check,
  copy: Copy,
  "git-merge": GitMerge,
  "git-fork": GitFork,
  route: Route,
  trash: Trash2,
  refresh: RefreshCw,
  menu: Menu,
  "arrow-right": ArrowRight,
  "panel-left-close": PanelLeftClose,
  "panel-left-open": PanelLeftOpen,
  "panel-right": PanelRight,
  send: SendHorizontal,
} satisfies Record<string, Component>;

export type GameIconName = keyof typeof gameIcons;

export const gameIconNames = Object.keys(gameIcons) as GameIconName[];
